global proc string GetPath()
{
	string $place=`whatIs GetPath`;
	string $buffer[];
 	$numTokens = `tokenize $place ":" $buffer`;
	$place=strip ($buffer[1]+":"+$buffer[2]);
	string $buffer1[];
 	$numTokens = `tokenize $place "/" $buffer1`;
	$place=$buffer1[0];
	for ($i=1;$i<($numTokens-1);$i++)
	{
		$place=$place+"/"+$buffer1[$i];
		
	}
	
	return	$place;	
}
$getPlace = GetPath();
python("getPlace = \""+$getPlace+"\"");

int $v=`about -v`;
print($getPlace);

if ($v>=2018)
{
	if ($v>=2022)
	{
		python("exec(open(\""+$getPlace+"/setAnimIcon.py\", encoding=\'utf-8\').read())");
	}else{
		python("execfile(\""+$getPlace+"/setAnimIcon.py\")");
	}

}